/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class isens_hba1c_analyzer_GpioPort */

#ifndef _Included_isens_hba1c_analyzer_GpioPort
#define _Included_isens_hba1c_analyzer_GpioPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     isens_hba1c_analyzer_GpioPort
 * Method:    Open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_isens_hba1c_1analyzer_GpioPort_Open
  (JNIEnv *, jobject);

/*
 * Class:     isens_hba1c_analyzer_GpioPort
 * Method:    Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_isens_hba1c_1analyzer_GpioPort_Close
  (JNIEnv *, jobject);

/*
 * Class:     isens_hba1c_analyzer_GpioPort
 * Method:    GpioControl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_isens_hba1c_1analyzer_GpioPort_GpioControl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     isens_hba1c_analyzer_GpioPort
 * Method:    unimplementedOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_isens_hba1c_1analyzer_GpioPort_unimplementedOpen
  (JNIEnv *, jobject);

/*
 * Class:     isens_hba1c_analyzer_GpioPort
 * Method:    unimplementedClose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_isens_hba1c_1analyzer_GpioPort_unimplementedClose
  (JNIEnv *, jobject);

/*
 * Class:     isens_hba1c_analyzer_GpioPort
 * Method:    unimplementedGpioControl
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_isens_hba1c_1analyzer_GpioPort_unimplementedGpioControl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
