/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class isens_hba1c_analyzer_SerialPort */

#ifndef _Included_isens_hba1c_analyzer_SerialPort
#define _Included_isens_hba1c_analyzer_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     isens_hba1c_analyzer_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_isens_hba1c_1analyzer_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     isens_hba1c_analyzer_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_isens_hba1c_1analyzer_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
